"""initial schema

Revision ID: 0dedc6c7eee7
Revises: 
Create Date: 2026-07-16 19:36:58.121171

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0dedc6c7eee7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('secret_encrypted', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=True),
    sa.Column('read_only_detail', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_connection_tenant_name')
    )
    op.create_index(op.f('ix_connections_tenant_id'), 'connections', ['tenant_id'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=32), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('sql_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('sql_row_limit', sa.Integer(), nullable=False),
    sa.Column('sql_max_cost', sa.Float(), nullable=False),
    sa.Column('sql_max_concurrent_per_connection', sa.Integer(), nullable=False),
    sa.Column('quality_weights', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('column_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('sampled', sa.Boolean(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('row_count_estimate', sa.Integer(), nullable=True),
    sa.Column('null_rate', sa.Float(), nullable=True),
    sa.Column('distinct_count', sa.Integer(), nullable=True),
    sa.Column('distinct_ratio', sa.Float(), nullable=True),
    sa.Column('min_value', sa.String(), nullable=True),
    sa.Column('max_value', sa.String(), nullable=True),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('avg_length', sa.Float(), nullable=True),
    sa.Column('declared_type', sa.String(length=128), nullable=True),
    sa.Column('detected_type', sa.String(length=64), nullable=True),
    sa.Column('pii_type', sa.String(length=32), nullable=True),
    sa.Column('top_values', sa.JSON(), nullable=False),
    sa.Column('sample_values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_profiles_connection_id'), 'column_profiles', ['connection_id'], unique=False)
    op.create_table('profiling_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('tables_total', sa.Integer(), nullable=False),
    sa.Column('tables_done', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiling_jobs_connection_id'), 'profiling_jobs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_profiling_jobs_tenant_id'), 'profiling_jobs', ['tenant_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('user_ref', sa.String(length=255), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('sql', sa.String(), nullable=False),
    sa.Column('tables_used', sa.JSON(), nullable=False),
    sa.Column('columns_used', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_connection_id'), 'query_logs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_query_logs_tenant_id'), 'query_logs', ['tenant_id'], unique=False)
    op.create_table('schema_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_snapshots_connection_id'), 'schema_snapshots', ['connection_id'], unique=False)
    op.create_table('db_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('from_schema', sa.String(length=255), nullable=False),
    sa.Column('from_table', sa.String(length=255), nullable=False),
    sa.Column('from_column', sa.String(length=255), nullable=False),
    sa.Column('to_schema', sa.String(length=255), nullable=False),
    sa.Column('to_table', sa.String(length=255), nullable=False),
    sa.Column('to_column', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('cardinality', sa.String(length=16), nullable=True),
    sa.Column('integrity_ratio', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['schema_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_relations_snapshot_id'), 'db_relations', ['snapshot_id'], unique=False)
    op.create_table('db_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=32), nullable=False),
    sa.Column('estimated_rows', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['schema_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_tables_snapshot_id'), 'db_tables', ['snapshot_id'], unique=False)
    op.create_table('db_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['db_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_columns_table_id'), 'db_columns', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_columns_table_id'), table_name='db_columns')
    op.drop_table('db_columns')
    op.drop_index(op.f('ix_db_tables_snapshot_id'), table_name='db_tables')
    op.drop_table('db_tables')
    op.drop_index(op.f('ix_db_relations_snapshot_id'), table_name='db_relations')
    op.drop_table('db_relations')
    op.drop_index(op.f('ix_schema_snapshots_connection_id'), table_name='schema_snapshots')
    op.drop_table('schema_snapshots')
    op.drop_index(op.f('ix_query_logs_tenant_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_connection_id'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_profiling_jobs_tenant_id'), table_name='profiling_jobs')
    op.drop_index(op.f('ix_profiling_jobs_connection_id'), table_name='profiling_jobs')
    op.drop_table('profiling_jobs')
    op.drop_index(op.f('ix_column_profiles_connection_id'), table_name='column_profiles')
    op.drop_table('column_profiles')
    op.drop_table('tenant_settings')
    op.drop_index(op.f('ix_connections_tenant_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
