"""quality scores + profile audit counts

Revision ID: 266acee1b8f0
Revises: 0dedc6c7eee7
Create Date: 2026-07-16 20:33:42.671716

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '266acee1b8f0'
down_revision: str | None = '0dedc6c7eee7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('relation_ref', sa.String(length=512), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_scores_connection_id'), 'quality_scores', ['connection_id'], unique=False)
    op.add_column('column_profiles', sa.Column('null_count', sa.Integer(), nullable=True))
    op.add_column('column_profiles', sa.Column('non_null_count', sa.Integer(), nullable=True))
    op.add_column('column_profiles', sa.Column('invalid_count', sa.Integer(), nullable=True))
    op.add_column('column_profiles', sa.Column('format_checked', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_profiles', 'format_checked')
    op.drop_column('column_profiles', 'invalid_count')
    op.drop_column('column_profiles', 'non_null_count')
    op.drop_column('column_profiles', 'null_count')
    op.drop_index(op.f('ix_quality_scores_connection_id'), table_name='quality_scores')
    op.drop_table('quality_scores')
    # ### end Alembic commands ###
