"""business concepts and mappings

Revision ID: 4cfc02ed6170
Revises: 266acee1b8f0
Create Date: 2026-07-17 07:19:10.114284

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4cfc02ed6170'
down_revision: str | None = '266acee1b8f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_concept_tenant_name')
    )
    op.create_index(op.f('ix_business_concepts_tenant_id'), 'business_concepts', ['tenant_id'], unique=False)
    op.create_table('concept_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('needs_arbitration', sa.Boolean(), nullable=False),
    sa.Column('arbitration_note', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['business_concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'schema_name', 'table_name', 'column_name', 'concept_id', name='uq_mapping_column_concept')
    )
    op.create_index(op.f('ix_concept_mappings_concept_id'), 'concept_mappings', ['concept_id'], unique=False)
    op.create_index(op.f('ix_concept_mappings_connection_id'), 'concept_mappings', ['connection_id'], unique=False)
    op.create_index(op.f('ix_concept_mappings_status'), 'concept_mappings', ['status'], unique=False)
    op.create_index(op.f('ix_concept_mappings_tenant_id'), 'concept_mappings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_mappings_tenant_id'), table_name='concept_mappings')
    op.drop_index(op.f('ix_concept_mappings_status'), table_name='concept_mappings')
    op.drop_index(op.f('ix_concept_mappings_connection_id'), table_name='concept_mappings')
    op.drop_index(op.f('ix_concept_mappings_concept_id'), table_name='concept_mappings')
    op.drop_table('concept_mappings')
    op.drop_index(op.f('ix_business_concepts_tenant_id'), table_name='business_concepts')
    op.drop_table('business_concepts')
    # ### end Alembic commands ###
