"""definitions, alerts, tenant preferences

Revision ID: d2e85e9ebf20
Revises: 4cfc02ed6170
Create Date: 2026-07-17 13:48:23.425324

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd2e85e9ebf20'
down_revision: str | None = '4cfc02ed6170'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('expression', sa.String(), nullable=True),
    sa.Column('filter_sql', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source_question', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_definition_tenant_name')
    )
    op.create_index(op.f('ix_business_definitions_tenant_id'), 'business_definitions', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=True),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('expression', sa.String(), nullable=True),
    sa.Column('filter_sql', sa.String(), nullable=True),
    sa.Column('comparison', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('last_message', sa.String(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['definition_id'], ['business_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_connection_id'), 'alerts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.add_column(
        'tenant_settings',
        sa.Column('preferences', sa.JSON(), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'preferences')
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_connection_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_business_definitions_tenant_id'), table_name='business_definitions')
    op.drop_table('business_definitions')
    # ### end Alembic commands ###
